project:
  type: website

website:
  favicon: images/favicon.ico
  sidebar:
    style: "docked"
    title: "STAT 133"
    logo: stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-stat133/spring-2024
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: data.qmd
        text: Datasets
      - href: cheatsheets.qmd
        text: Cheatsheets
      - section: "Units"
        contents:
          - units/unit1.qmd
          - units/unit2.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



