project:
  type: website

website:
  favicon: images/favicon.ico
  sidebar:
    style: "docked"
    title: "STAT 133"
    logo: stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-stat133/spring-2024
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: about.qmd
        text: About
      - href: staff.qmd
        text: Staff
      - href: data.qmd
        text: Datasets
      - href: cheatsheets.qmd
        text: Cheatsheets
      - section: "Units"
        contents:
          - units/unit1.qmd
          - units/unit2.qmd
          - units/unit3.qmd
          - units/unit4.qmd
          - units/unit5.qmd
          - units/unit6.qmd
          - units/unit7.qmd
          - units/unit8.qmd
          - units/unit9.qmd
          - units/unit10.qmd
          - units/unit11.qmd
          - units/unit12.qmd
          - units/unit13.qmd
          - units/unit14.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



