---
title: "Unit 6: Tables and Tidyverse-2"
format:
  html:
    code-fold: show
    code-tools: true
---


## 📖 Lecture

This week we continue with another fundamental tidyverse package `"dplyr"`. Simply put, **dplyr** comes with functions that allow you to manipulate data-tables (e.g. data-frames, and other 2-dimensional objects) using a modern and syntactic way.

 

## 📚 Reading

Read chapters 5 to 10 of "R Tidy Hurricanes":

- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/2-02-intro-dplyr.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/2-02-intro-dplyr.html</a>
- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/2-03-intro-pipes.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/2-03-intro-pipes.html</a>
- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/3-01-storms-year.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/3-01-storms-year.html</a>
- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/3-02-storms-1975.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/3-02-storms-1975.html</a>
- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/3-03-amy-1975.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/3-03-amy-1975.html</a>
- <a href="https://www.gastonsanchez.com/R-tidy-hurricanes/3-04-summary-1975.html" target="_blank">https://www.gastonsanchez.com/R-tidy-hurricanes/3-04-summary-1975.html</a>



## 🔬 Lab

You will get to practice common manipulation operations of data-tables using a modern and syntactic way following the data plying framework provided by the R package dplyr.

Also, we are going to review various aspects that have to do with reading in (i.e. importing) tables in R.



## 🎯 Objectives

Perform basic manipulations on data tables with "dplyr" functions:

- Select rows with `slice()`, and `filter()`
- Select columns with `select()`
- Transform columns with `mutate()`
- Arrange rows with `arrange()`
- Group data with `group_by()`
- Summarize data with `summarize()`



## 🔆 Shiny Friday

The shiny app for this week, like in the previous week, involves data from NBA players. This time, the goal is to visualize scatter plots with ggplot2.

We have three versions:

- __nba-scatterplots1-basic__: produces a simple scatterplot based on two select inputs, one to select the variable of the x-axis, the other one to select the variable of the y-axis. <br>
<a href="https://github.com/data133/shiny/tree/main/nba-scatterplots1-basic" target="_blank">https://github.com/data133/shiny/tree/main/nba-scatterplots1-basic</a>

- __nba-scatterplots2-ggplotly__: same as app1 but this takes the ggplot object and makes it into a plotly object. <br>
<a href="https://github.com/data133/shiny/tree/main/nba-scatterplots2-ggplotly" target="_blank">https://github.com/data133/shiny/tree/main/nba-scatterplots2-ggplotly</a>

- __nba-scatterplots3-smoother1__: same as app1, plus radio buttons to decide whether to add a smoother. <br>
<a href="https://github.com/data133/shiny/tree/main/nba-scatterplots3-smoother1" target="_blank">https://github.com/data133/shiny/tree/main/nba-scatterplots3-smoother1</a>


## 🔔 Assignments

- HW4 due this 02/23
- HW5 released on 02/24, due 03/01
